[versions]
minestom = "2026.01.08-1.21.11"
velocity = "3.5.0-SNAPSHOT"
lettuce = "7.4.0.RELEASE"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
lettuce = { group = "io.lettuce", name = "lettuce-core", version.ref = "lettuce" }
